name: Claim epic games

on:
  #watch:
    #types: [started] # uncomment to manually activate it by starring your repo
  schedule:
    - cron: "0 5,17 * * *"
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore claimer

    - name: Claim games

      run: |

        $Env:epicname="${{secrets.USERNAME}}"

        $Env:epicpass="${{secrets.PASS}}"

        $Env:captcha="${{secrets.CAPTCHA}}"

        dotnet run --project claimer/claimer/claimer.csproj

        $Env:epicname="${{secrets.USERNAME2}}"

        $Env:epicpass="${{secrets.PASS2}}"

        $Env:captcha="${{secrets.CAPTCHA2}}"

        dotnet run --project claimer/claimer/claimer.csproj
        
        $Env:epicname="${{secrets.USERNAME3}}"

        $Env:epicpass="${{secrets.PASS3}}"

        $Env:captcha="${{secrets.CAPTCHA3}}"

        dotnet run --project claimer/claimer/claimer.csproj

        $Env:epicname="${{secrets.USERNAME4}}"

        $Env:epicpass="${{secrets.PASS4}}"

        $Env:captcha="${{secrets.CAPTCHA4}}"

        dotnet run --project claimer/claimer/claimer.csproj
